#!/bin/sh

MESSAGE_FILE="$1"
SOURCE="$2"
SHA1="$3"

echo "Prepare-commit-msg hook running symgit in commitOnly mode"

# Read commit message
commitMsg="$(printf "%s" "$(cat "$MESSAGE_FILE")" | tr -d '\r\n')"

# Run symgit in commitOnly mode
dotnet fsi symgit.fsx commitOnly -all -msg "$commitMsg"

